/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Loi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpMenu = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cmdKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cmdTheLoai = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cmdSach = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cmdLop = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cmdSV = new javax.swing.JMenuItem();
        cmdPhieu = new javax.swing.JMenu();
        cmdPhieuMuon = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        cmdPhieuTra = new javax.swing.JMenuItem();
        ad = new javax.swing.JMenu();
        cmdTimPhieu = new javax.swing.JMenuItem();
        cmdTimSach = new javax.swing.JMenuItem();
        cmdTimSV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tbpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 1000, 700));

        jMenu1.setText("Hệ Thống");

        cmdKetThuc.setText("Kết Thúc");
        cmdKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(cmdKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Danh Mục");

        cmdTheLoai.setText("Danh Mục Thể Loại");
        cmdTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTheLoaiActionPerformed(evt);
            }
        });
        jMenu2.add(cmdTheLoai);
        jMenu2.add(jSeparator1);

        cmdSach.setText("Danh Mục Sách");
        cmdSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSachActionPerformed(evt);
            }
        });
        jMenu2.add(cmdSach);
        jMenu2.add(jSeparator2);

        cmdLop.setText("Danh Mục Lớp");
        cmdLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLopActionPerformed(evt);
            }
        });
        jMenu2.add(cmdLop);
        jMenu2.add(jSeparator3);

        cmdSV.setText("Danh Mục Sinh Viên");
        cmdSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSVActionPerformed(evt);
            }
        });
        jMenu2.add(cmdSV);

        jMenuBar1.add(jMenu2);

        cmdPhieu.setText("Quản Lý Phiếu");

        cmdPhieuMuon.setText("Phiếu Mượn");
        cmdPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPhieuMuonActionPerformed(evt);
            }
        });
        cmdPhieu.add(cmdPhieuMuon);
        cmdPhieu.add(jSeparator4);

        cmdPhieuTra.setText("Phiếu Trả");
        cmdPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPhieuTraActionPerformed(evt);
            }
        });
        cmdPhieu.add(cmdPhieuTra);

        jMenuBar1.add(cmdPhieu);

        ad.setText("Tra Cứu");

        cmdTimPhieu.setText("Tìm Phiếu");
        cmdTimPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimPhieuActionPerformed(evt);
            }
        });
        ad.add(cmdTimPhieu);

        cmdTimSach.setText("Tìm Sách");
        cmdTimSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimSachActionPerformed(evt);
            }
        });
        ad.add(cmdTimSach);

        cmdTimSV.setText("Tìm Sinh viên");
        cmdTimSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimSVActionPerformed(evt);
            }
        });
        ad.add(cmdTimSV);

        jMenuBar1.add(ad);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonClose(String title) {
        int index = tbpMenu.indexOfTab(title);
        JPanel pnlTab = new JPanel(new GridBagLayout());
        pnlTab.setOpaque(false);
        JLabel lblTitle = new JLabel(title);
        JButton btnClose = new JButton("x");

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1;

        pnlTab.add(lblTitle, gbc);

        gbc.gridx++;
        gbc.weightx = 0;

        pnlTab.add(btnClose, gbc);

        tbpMenu.setTabComponentAt(index, pnlTab);
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Component selected = tbpMenu.getSelectedComponent();
                if (selected != null) {
                    tbpMenu.remove(selected);
                }
            }
        });
    }

    private void cmdSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSachActionPerformed
        if (tbpMenu.indexOfTab("Sách") <= -1) {
            tbpMenu.add("Sách", new DanhMucSach());
            ButtonClose("Sách");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Sách"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Sách"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdSachActionPerformed

    private void cmdPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPhieuTraActionPerformed
        if (tbpMenu.indexOfTab("Trả Sách") <= -1) {
            tbpMenu.add("Trả Sách", new QuanLyTraSach());
            ButtonClose("Trả Sách");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Trả Sách"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Trả Sách"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdPhieuTraActionPerformed

    private void cmdTimSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimSVActionPerformed
        if (tbpMenu.indexOfTab("Tìm Sinh Viên") <= -1) {
            tbpMenu.add("Tìm Sinh Viên", new TraCuuSinhVien());
            ButtonClose("Tìm Sinh Viên");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Sinh Viên"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Sinh Viên"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdTimSVActionPerformed

    private void cmdTimPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimPhieuActionPerformed
        if (tbpMenu.indexOfTab("Tìm Phiếu") <= -1) {
            tbpMenu.add("Tìm Phiếu", new TraCuuPhieu());
            ButtonClose("Tìm Phiếu");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Phiếu"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Phiếu"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdTimPhieuActionPerformed

    private void cmdKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKetThucActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdKetThucActionPerformed

    private void cmdTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTheLoaiActionPerformed
        if (tbpMenu.indexOfTab("Thể Loại") <= -1) {
            tbpMenu.add("Thể Loại", new DanhMucTheLoai());
            ButtonClose("Thể Loại");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Thể Loại"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Thể Loại"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdTheLoaiActionPerformed

    private void cmdLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLopActionPerformed
        if (tbpMenu.indexOfTab("Lớp") <= -1) {
            tbpMenu.add("Lớp", new DanhMucLop());
            ButtonClose("Lớp");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Lớp"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Lớp"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdLopActionPerformed

    private void cmdSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSVActionPerformed
        if (tbpMenu.indexOfTab("Sinh Viên") <= -1) {
            tbpMenu.add("Sinh Viên", new DanhMucSinhVien());
            ButtonClose("Sinh Viên");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Sinh Viên"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Sinh Viên"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdSVActionPerformed

    private void cmdPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPhieuMuonActionPerformed
        if (tbpMenu.indexOfTab("Mượn Sách") <= -1) {
            tbpMenu.add("Mượn Sách", new QuanLyMuonSach());
            ButtonClose("Mượn Sách");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Mượn Sách"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Mượn Sách"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdPhieuMuonActionPerformed

    private void cmdTimSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimSachActionPerformed
        if (tbpMenu.indexOfTab("Tìm Sách") <= -1) {
            tbpMenu.add("Tìm Sách", new TraCuuSach());
            ButtonClose("Tìm Sách");
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Sách"));
        } else {
            tbpMenu.setSelectedIndex(tbpMenu.indexOfTab("Tìm Sách"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở !");
        }
    }//GEN-LAST:event_cmdTimSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ad;
    private javax.swing.JMenuItem cmdKetThuc;
    private javax.swing.JMenuItem cmdLop;
    private javax.swing.JMenu cmdPhieu;
    private javax.swing.JMenuItem cmdPhieuMuon;
    private javax.swing.JMenuItem cmdPhieuTra;
    private javax.swing.JMenuItem cmdSV;
    private javax.swing.JMenuItem cmdSach;
    private javax.swing.JMenuItem cmdTheLoai;
    private javax.swing.JMenuItem cmdTimPhieu;
    private javax.swing.JMenuItem cmdTimSV;
    private javax.swing.JMenuItem cmdTimSach;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane tbpMenu;
    // End of variables declaration//GEN-END:variables
}
