/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Loi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpMenu = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cmdKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cmdTheLoai = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cmdSach = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cmdLop = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cmdSV = new javax.swing.JMenuItem();
        cmdPhieuMuon = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        cmdPhieuTra = new javax.swing.JMenuItem();
        ad = new javax.swing.JMenu();
        cmdTimPhieu = new javax.swing.JMenuItem();
        cmdTimSach = new javax.swing.JMenuItem();
        cmdTimSV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Hệ Thống");

        cmdKetThuc.setText("Kết Thúc");
        jMenu1.add(cmdKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Danh Mục");

        cmdTheLoai.setText("Thể Loại");
        jMenu2.add(cmdTheLoai);
        jMenu2.add(jSeparator1);

        cmdSach.setText("Danh Mục Sách");
        cmdSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSachActionPerformed(evt);
            }
        });
        jMenu2.add(cmdSach);
        jMenu2.add(jSeparator2);

        cmdLop.setText("Danh Mục Lớp");
        jMenu2.add(cmdLop);
        jMenu2.add(jSeparator3);

        cmdSV.setText("Danh Mục Sinh Viên");
        jMenu2.add(cmdSV);

        jMenuBar1.add(jMenu2);

        cmdPhieuMuon.setText("Quản Lý Phiếu");

        jMenuItem6.setText("Phiếu Mượn");
        cmdPhieuMuon.add(jMenuItem6);
        cmdPhieuMuon.add(jSeparator4);

        cmdPhieuTra.setText("Phiếu Trả");
        cmdPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPhieuTraActionPerformed(evt);
            }
        });
        cmdPhieuMuon.add(cmdPhieuTra);

        jMenuBar1.add(cmdPhieuMuon);

        ad.setText("Tra Cứu");

        cmdTimPhieu.setText("Tìm Phiếu");
        cmdTimPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimPhieuActionPerformed(evt);
            }
        });
        ad.add(cmdTimPhieu);

        cmdTimSach.setText("Tìm Sách");
        ad.add(cmdTimSach);

        cmdTimSV.setText("Tìm Sinh viên");
        cmdTimSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTimSVActionPerformed(evt);
            }
        });
        ad.add(cmdTimSV);

        jMenuBar1.add(ad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(tbpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSachActionPerformed

    private void cmdPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPhieuTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdPhieuTraActionPerformed

    private void cmdTimSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdTimSVActionPerformed

    private void cmdTimPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTimPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdTimPhieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ad;
    private javax.swing.JMenuItem cmdKetThuc;
    private javax.swing.JMenuItem cmdLop;
    private javax.swing.JMenu cmdPhieuMuon;
    private javax.swing.JMenuItem cmdPhieuTra;
    private javax.swing.JMenuItem cmdSV;
    private javax.swing.JMenuItem cmdSach;
    private javax.swing.JMenuItem cmdTheLoai;
    private javax.swing.JMenuItem cmdTimPhieu;
    private javax.swing.JMenuItem cmdTimSV;
    private javax.swing.JMenuItem cmdTimSach;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane tbpMenu;
    // End of variables declaration//GEN-END:variables
}
